# Generated by Django 3.0.4 on 2020-04-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='Files',
            field=models.FileField(null=True, upload_to='images/', verbose_name=''),
        ),
    ]
