# Generated by Django 3.0.4 on 2020-04-02 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_projects_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='enddate',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='startdate',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
