# Generated by Django 3.0.4 on 2020-04-02 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200402_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='Files',
            field=models.FileField(blank=True, null=True, upload_to='images/', verbose_name=''),
        ),
    ]
