# Generated by Django 3.0.4 on 2020-04-04 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_achievement_extracurricular_grades'),
    ]

    operations = [
        migrations.AddField(
            model_name='grades',
            name='Institute',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
