# Generated by Django 3.0.4 on 2020-04-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200404_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grades',
            name='Institute',
            field=models.CharField(default='Indian Institute of Technology, Roorkee', max_length=200, null=True),
        ),
    ]
