# Generated by Django 3.0.5 on 2020-04-08 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200408_1102'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
