# Generated by Django 3.0.5 on 2020-04-08 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20200408_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='extracurricular',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Customer'),
        ),
    ]
